version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 5
    groups:
      composer-minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      composer-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
