# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    # To change session storage in production, set SESSION_HANDLER_DSN:
    #   Redis: redis://localhost:6379  |  PDO: %env(DATABASE_URL)%
    session:
        handler_id: null

    #esi: true
    #fragments: true

when@dev:
    framework:
        session:
            handler_id: '%env(DATABASE_URL)%'

when@prod:
    framework:
        session:
            handler_id: '%env(SESSION_HANDLER_DSN)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
