/*
 * This file is part of the Expanded Decks project.
 *
 * (c) Expanded Decks contributors
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Build-time generated list of Pokemon sprite slugs.
 * The actual file is generated by webpack.config.js before each build.
 *
 * @see docs/features.md F2.22 — Custom Pokemon sprites on decks
 */
declare module '*/generated/pokemon-sprites.json' {
    const slugs: string[];
    export default slugs;
}
